"""Create MRI embeddings and participant metadata

Revision ID: e396a334a3d2
Revises: 
Create Date: 2025-08-03 12:47:34.786861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e396a334a3d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_metadata_id'), 'participant_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_participant_metadata_participant_id'), 'participant_metadata', ['participant_id'], unique=True)
    op.create_table('mri_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=True),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant_metadata.participant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mri_embeddings')
    op.drop_index(op.f('ix_participant_metadata_participant_id'), table_name='participant_metadata')
    op.drop_index(op.f('ix_participant_metadata_id'), table_name='participant_metadata')
    op.drop_table('participant_metadata')
    # ### end Alembic commands ###
